robot_name: 'go2'

joint_names: &jn ["LF_HAA", "LF_HFE", "LF_KFE", "LH_HAA", "LH_HFE", "LH_KFE", "RF_HAA", "RF_HFE", "RF_KFE", "RH_HAA", "RH_HFE", "RH_KFE"]
base_name: "base"

state_topic: "anymal_d/state"
command_topic: "anymal_d/command"
change_controller_topic: "anymal_d/change_controller"
contact_topics: ["/lf_foot_contact", "/rf_foot_contact", "/lh_foot_contact","/rh_foot_contact"] 


marker_topic: "markers"
odom_frame: "odom"

state_publisher:
  update_rate: 400 # Hz

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.806, -1.802, 0.0, 0.996, -1.802, 0.0, 0.806, -1.802, 0.0, 0.996, -1.802] # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65] # LF, LH, RF, RH
  kp: 90
  kd: 0.5
  interpolation_time: 1.0 # s
  rate: 50 # Hz

bob_controller:
  blind: true
  kp: 30.0
  kd: 0.5

  hf_repo: "kubjonai/tbai-models"
  hf_model: "go2_blind.pt"
  
  action_scale: 0.25
  lin_vel_scale: 2.0

  default_stance: [
    [ 0.025,  0.096, -0.263],
    [-0.025,  0.096, -0.263],
    [ 0.025, -0.096, -0.263],
    [-0.025, -0.096, -0.263],
  ]

  ik:
    d2: 0.0955
    a3: 0.213
    a4: 0.213

  cpg:
    period: 0.6
    time_offsets: [0.0, 0.3, 0.3, 0.0]  # LF, LH, RF, RH
    swing_height: 0.1

wtw_controller:
  kp: 25.0
  kd: 0.6

reference_generator:
  type: "twist"

  joystick:
    topic: "joy"
    ramped_velocity: 5.0
    x_index: 1
    y_index: 0
    yaw_index: 3
    x_scale: 1.0
    y_scale: 0.5
    yaw_scale: 0.5

  twist:
    topic: "cmd_vel"


anymal_d:
  joint_controller:
      type: tbai_ros_gazebo/JointController
      joints: *jn

contact_sensor:
  update_rate: 20 # Hz