repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check .
        language: system
        always_run: true
        pass_filenames: false

      - id: ruff-format
        name: ruff-format
        entry: python3 -m ruff format .
        language: system
        always_run: true
        pass_filenames: false
